#!/bin/sh
MTU_SIZE=0 
MAXIMUM_MTU_SIZE=65507
RETURNED_PING_ANSWER=1 
CURRENT_MTU_POINTER=65507 
TARGET_IP_ADDRESS="172.17.0.2"

returnPingAnswer(){
	local MTU_SIZE=$1
	local CURRENT_MTU=$2
	local TARGET_IP_ADDRESS=$3
	#CURTO CIRCUIT ("JUMP") THE ERROR OUTPUT WITH DEFAULT ONE
	RETURNED_PING_ANSWER=`ping -c 1 -s$((MTU_SIZE+CURRENT_MTU)) -Mdo $TARGET_IP_ADDRESS 2>&1 | grep '1 received'`
	echo $RETURNED_PING_ANSWER
}

updateTotalMtuSize(){
	local TOTAL_MTU_SIZE=$1
	local CURRENT_MTU_SIZE=$2
	local RETURNED_PING_ANSWER=$3

	if [ "$RETURNED_PING_ANSWER" != "" ]; then
		TOTAL_MTU_SIZE=$((TOTAL_MTU_SIZE+CURRENT_MTU_SIZE))
	fi
	echo $TOTAL_MTU_SIZE
}

calculateNewCurrentMtuPointer(){
	local CURRENT_MTU=$1
	CURRENT_MTU=$((CURRENT_MTU/2))
	echo $CURRENT_MTU
}

calculateMtu(){
	local CURRENT_MTU_POINTER=$1
	local RETURNED_PING_ANSWER=$2
	local MTU_SIZE=$3
	local TARGET_IP_ADDRESS=$4
	local MINIMUM_MTU_VALUE=0

	while [ "$CURRENT_MTU_POINTER" != $MINIMUM_MTU_VALUE ]
		do
			RETURNED_PING_ANSWER=$(returnPingAnswer $MTU_SIZE $CURRENT_MTU_POINTER $TARGET_IP_ADDRESS)
			MTU_SIZE=$(updateTotalMtuSize $MTU_SIZE $CURRENT_MTU_POINTER $RETURNED_PING_ANSWER)
			CURRENT_MTU_POINTER=$(calculateNewCurrentMtuPointer $CURRENT_MTU_POINTER)
	done
	echo $MTU_SIZE
}

MTU=$(calculateMtu $CURRENT_MTU_POINTER "$RETURNED_PING_ANSWER" "$MTU_SIZE" "$TARGET_IP_ADDRESS")

echo "The MTU (Maximum Transfer Unit) is: $MTU"
 
